create sequence primary_sequence start with 10000 increment by 1;
create table administrator (administrator_id integer not null, administrator_email varchar(50) not null unique, administrator_ime varchar(50) not null, administrator_prezime varchar(50) not null, administrator_sifra varchar(200) not null, primary key (administrator_id));
create table atribut (atribut_id integer not null, atribut_opis varchar(200) not null, primary key (atribut_id));
create table dogadaj (dogadaj_id integer not null, trgovina_id integer not null, dogadaj_naziv varchar(50) not null, dogadaj_opis varchar(50), dogadaj_slika varchar(50) not null, dogadaj_vrijeme varchar(50) not null, primary key (dogadaj_id));
create table ima_atribute (atribut_id integer not null, trgovina_id integer not null, primary key (atribut_id, trgovina_id));
create table kupac (kupac_id integer not null, kupac_ime varchar(20) not null, kupac_prezime varchar(20) not null, kupac_adresa varchar(50) not null, kupac_email varchar(50) not null unique, kupac_sifra varchar(200) not null, primary key (kupac_id));
create table kupac_dogadaj (dogadaj_id integer not null, kupac_dogadaj_flag boolean not null, kupac_id integer not null, id bigint not null, primary key (id));
create table kupac_ponuda_popust (kupac_id integer not null, kupac_ponuda_popust_flag boolean not null, ponuda_popust_id integer not null, id bigint not null, primary key (id));
create table kupac_proizvod (kolicina_proizvoda integer not null, kupac_id integer not null, proizvod_id integer not null, id bigint not null, racun_id bigint, primary key (id));
create table moderator (moderator_id integer not null, moderator_email varchar(50) not null unique, moderator_ime varchar(50) not null, moderator_prezime varchar(50) not null, moderator_sifra varchar(200) not null, primary key (moderator_id));
create table ocjena_proizvod_kupac (kupac_id integer not null, ocjena integer not null, proizvod_id integer not null, id bigint not null, primary key (id));
create table ponuda (ponuda_id integer not null, ponuda_popust_id integer not null, ponuda_naziv varchar(100) not null, ponuda_opis varchar(200) not null, primary key (ponuda_id));
create table ponuda_popust (ponuda_popust_flag boolean not null, ponuda_popust_id integer not null, trgovina_id integer not null, primary key (ponuda_popust_id));
create table popust (ponuda_popust_id integer not null, popust_id integer not null, popust_qrkod varchar(50) not null, popust_naziv varchar(100) not null, popust_opis varchar(200) not null, primary key (popust_id));
create table proizvod (proizvod_cijena float(53) not null, proizvod_flag boolean not null, proizvod_id integer not null, trgovina_id integer not null, proizvod_kategorija varchar(50) not null, proizvod_naziv varchar(50) not null, proizvod_opis varchar(200), proizvod_slika varchar(200) not null, primary key (proizvod_id));
create table racun (kupac_id integer not null, placen boolean not null, trgovina_id integer not null, racun_id bigint not null, vrijeme_datum_nastanka timestamp(6) not null, primary key (racun_id));
create table recenzija (kupac_id integer not null, odobrio_moderator boolean not null, recenzija_id integer not null, recenzija_zvjezdice integer not null, trgovina_id integer not null, vrijeme_kreiranja timestamp(6) not null, recenzija_odgovor varchar(500), recenzija_opis varchar(500), primary key (recenzija_id));
create table trgovina (trgovina_id integer not null, trgovina_radno_vrijeme_do varchar(5) not null, trgovina_radno_vrijeme_od varchar(5) not null, trgovina_lokacija varchar(50) not null, trgovina_email varchar(100) not null, trgovina_naziv varchar(100) not null, trgovina_sifra varchar(200) not null, trgovina_slika varchar(200) not null, trgovina_kategorija varchar(500) not null, trgovina_opis varchar(500) not null, primary key (trgovina_id));
alter table if exists dogadaj add constraint FKg7ryqhcd9tw6tvpmwynrvpe0r foreign key (trgovina_id) references trgovina;
alter table if exists ima_atribute add constraint FK41m8ltoxmw2ltoaj21e14h12u foreign key (atribut_id) references atribut;
alter table if exists ima_atribute add constraint FKjr3pk5tf0v926ehroq0gbe63u foreign key (trgovina_id) references trgovina;
alter table if exists kupac_dogadaj add constraint FKlylkl7r5koyaci12n0tldam5u foreign key (dogadaj_id) references dogadaj;
alter table if exists kupac_dogadaj add constraint FKt1puoe1qouydpnebu67km53yr foreign key (kupac_id) references kupac;
alter table if exists kupac_ponuda_popust add constraint FKhqukegtdx24bnb9pbhtwoahrr foreign key (kupac_id) references kupac;
alter table if exists kupac_ponuda_popust add constraint FKh3t14ptcky3car1nx3qrdy1b9 foreign key (ponuda_popust_id) references ponuda_popust;
alter table if exists kupac_proizvod add constraint FK4n6kncmobup2t8n650wnfu5jo foreign key (kupac_id) references kupac;
alter table if exists kupac_proizvod add constraint FKfjum6keglho667f9yuoqs0eva foreign key (proizvod_id) references proizvod;
alter table if exists kupac_proizvod add constraint FKs5dwsyuovn1r02e9r4s6d74g7 foreign key (racun_id) references racun;
alter table if exists ocjena_proizvod_kupac add constraint FK2lxat3cq4h3ov2cyc15mh6ttk foreign key (kupac_id) references kupac;
alter table if exists ocjena_proizvod_kupac add constraint FKk5ttr2mxwu6xwd6kiya5wvrns foreign key (proizvod_id) references proizvod;
alter table if exists ponuda add constraint FK2i108f5w929glikjjh17aaa16 foreign key (ponuda_popust_id) references ponuda_popust;
alter table if exists ponuda_popust add constraint FKlc07hvhfouasg1442rdh77k5c foreign key (trgovina_id) references trgovina;
alter table if exists popust add constraint FK1sh7u3eawau7gfhhlu3ai7ojo foreign key (ponuda_popust_id) references ponuda_popust;
alter table if exists proizvod add constraint FKj5b23skboeqmfb2yhrgod4s55 foreign key (trgovina_id) references trgovina;
alter table if exists racun add constraint FK15s8nktdlnm4vt86y0ipijhgm foreign key (kupac_id) references kupac;
alter table if exists racun add constraint FKan5dvknc2c7mhfgbyl1w0uh56 foreign key (trgovina_id) references trgovina;
alter table if exists recenzija add constraint FKrb7flu5y48v753hurf1kc6cbp foreign key (kupac_id) references kupac;
alter table if exists recenzija add constraint FK44hvicwg88hbfc98f8n1ed1yi foreign key (trgovina_id) references trgovina;
